### PR TITLE
Mention putting issue numbers in commit messages

### PR DESCRIPTION
**Pull request by kfogel**
@frjo and others,

In Hypha's commit history, sometimes the relevant issue number(s) is included in commit messages and sometimes not.  The "Contributing" documentation only talks about putting issue numbers in the related PR, not in commit messages themselves.  

Therefore, this PR is both a proposal and a question: do we want to put issue numbers in the commit messages?  The proposed answer is: "yes" :-).

Including issue numbers in commit messages means the commit<->issue connection would be memorialized in the actual Git history, not just in GitHub's PR records (which are not part of the Git history).

Now, one *could* respond by pointing out that the issue tickets themselves are also only in GitHub, not in the Git history.  However, I think that's not relevant, for three reasons:

1. Ticket numbers tend to get mentioned in a wide variety of places, so if a ticket number is mentioned in the commit history, then a thread of relatedness can be drawn among all the places that mention that issue -- the issue tracker being just one of those places.
2. One can (and people sometimes do) download issues in CSV/JSON format for off-GitHub archiving and processing, so there can be a record of issues independently of GitHub.
3. In any case, even if the issues are only on GitHub and nowhere else, it's still very useful to be able to go from commit logs straight to issue tickets.  There is *no* record of PR numbers in Git history, after all --- except for the rare cases where someone mentions a PR number, as opposed to an issue number, in a commit message (which rarely happens; see [commit 3d2e02a16e](https://github.com/HyphaApp/hypha/commit/3d2e02a16e38894282ebf2f5f79eab405a61c784) in Hypha, for example: how would someone know which PR it's referring to?).  It's quite hard to go from the Git history to the corresponding issue tickets unless the tickets are explicitly named in the commit logs, and yet it is often *useful* to go from Git history to corresponding issues.

Therefore, let us make the history->issue jump possible.

Thoughts?

### CODE REVIEW

**Comment by slifty** [comment]
Fully agree!

Also, if we don't link to this explicitly in our contributing MD I think we should consider it: https://cbea.ms/git-commit/

Every one of the seven commit message guidelines is a good one that we should adhere to!

**Comment by fourthletter** [comment]
@kfogel @slifty Thank you both for this feedback. We are moving toward a more thorough approach to documentation. Including issue number(s) in commit messages sounds like good practice to consider in our overall strategy.

**Comment by frjo** [comment]
@sandeepsajan0 @theskumar Should we try to start following this?

**Comment by sandeepsajan0** [comment]
@frjo Yes, I agree with this pattern. It'll be good for traceability. We can split our commit message into two parts: header and body. Where header can contain the action type like fix, resolve, and enhance with the issue number like fix #aaa, and the body can contain the message that we used to have right now. 
So, our commit message might look like this: `Fix #1234: Update ABCView to make it right...`.

**Comment by theskumar** [comment]
Instead of putting this on devs, we decided to use GitHub's squash and merge a PR feature to automatically set the PR number in the commit and have the option to include the issue number in the message body.

**Comment by frjo** [comment]
All future commits will look like this https://github.com/HyphaApp/hypha/commit/e94cd23088dba2621eb786c05f3611c372e16f96. No more merge commits. Thanks to @theskumar for suggesting this improved workflow.

**Pull request closed without merging**
