### PR TITLE
Move documentation to MkDocs

### LINKED ISSUE #49: MkDocs on Netlify for documentation, replacing GitBook
https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/

This allows reviewer to see what the site actually changes like without having to pull the changes locally.

MkDocs: https://www.mkdocs.org/

### PR DESCRIPTION
**Pull request by frjo**
Fixes #49

### CODE REVIEW

**Comment by frjo** [comment]
@theskumar If you have any configuration/plugins etc. that you think make obvious sense here, please do not hesitate to add them to this PR.

**Comment by theskumar** [comment]
@frjo I'll take a look at the plugins and also the plugins customization we can also do as do more and more docs. More organically.

**Comment by frjo** [comment]
@theskumar Nice improvements. Really liking mkdocs, it just makes sense.

**Comment by frjo** [comment]
Updated the dev port to `9100` to avoid conflicts in my local env. I hope that works for you as well.

**Pull request merged**
